services:
  postgres:
    image: postgres:17
    container_name: maxspace-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: maxspace_user
      POSTGRES_PASSWORD: maxspace_password
      POSTGRES_DB: maxspace_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxspace_user -d maxspace_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: